apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app-dev
  name: web-app-dev
  namespace: brownbag
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: web-app-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-app-dev
    spec:
      containers:
        - image: colbyx20/brownbag-app:1.0
          name: brownbag-app
          resources: {}
