services:
  brownbag-app-prod:
    image: colbyx20/brownbag-app:1.0
    container_name: brown-bag-deploy-prod
    networks:
    - brownbag-dev-network 
    ports: 
    - "5000:5000"

networks:
  brownbag-prod-network:
    driver: bridge