services:
  brownbag-app-dev:
    image: colbyx20/brownbag-app:1.0.3.9
    container_name: brown-bag-deploy-dev
    networks:
      - brownbag-dev-network
    ports:
      - "5000:5000"
networks:
  brownbag-dev-network:
    driver: bridge
